#!/bin/env sh

# This is a pre-commit hook that auto-formats any commited source files
#  using Prettier for frontend (.js, .ts, .html) files
#  and Black for backend (.py) files


# Files to run Prettier on
PRETTIER_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.ts" "*.html" "*.css" "*.jsx" | sed 's| |\\ |g')

# Files to run Black on
BLACK_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.py")

if [ ! -z "$PRETTIER_FILES" ]; then
    # Prettify selected files
    echo "$PRETTIER_FILES" | xargs ./frontend/node_modules/.bin/prettier --write;

    # Add back the modified/prettified files to staging
    echo "$PRETTIER_FILES" | xargs git add;
fi


if [ ! -z "$BLACK_FILES" ]; then

    # Prettify selected files
    echo "$BLACK_FILES" | xargs ./backend/.venv/heatflask/bin/black;

    # Add back the modified/prettified files to staging
    echo "$BLACK_FILES" | xargs git add;
fi

# Clear outputs of Python notebooks
#  Outputs can make versioning notebook files unpleasant
IPYNB_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ipynb")
if [ ! -z "$IPYNB_FILES" ]; then

    echo "$IPYNB_FILES" | xargs jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace;

    # Add back the modified files to staging
    echo "$IPYNB_FILES" | xargs git add;
fi

exit 0
