#!/bin/env bash

# This is a pre-commit hook that auto-formats ceartain files

PRETTIER_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.ts" "*.html" "*.css" "*.jsx" | sed 's| |\\ |g')

if [ ! -z "$PRETTIER_FILES" ]; then
    # Prettify selected files
    echo "$PRETTIER_FILES" | xargs ./Client/node_modules/.bin/prettier --write;

    # Add back the modified/prettified files to staging
    echo "$PRETTIER_FILES" | xargs git add;
fi

BLACK_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.py")
if [ ! -z "$BLACK_FILES" ]; then

    # Prettify selected files
    echo "$BLACK_FILES" | xargs .venv/heatflask/bin/black;

    # Add back the modified/prettified files to staging
    echo "$BLACK_FILES" | xargs git add;
fi

# Clear outputs of Python notebooks
#  Outputs can make versioning notebook files unpleasant
IPYNB_FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ipynb")
if [ ! -z "$IPYNB_FILES" ]; then

    echo "$IPYNB_FILES" | xargs jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace;

    # Add back the modified files to staging
    echo "$IPYNB_FILES" | xargs git add;
fi

exit 0
