#!/usr/bin/env sh

# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.


changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Example usage
check_run frontend/package-lock.json "cd frontend; npm ci; cd .." &

check_run backend/requirements*.txt "cd backend; sh ./dev-install-backend; cd .."
