#!/bin/bash

source activate

export PORT=5000

while [ "$1" != "" ]; do
    case $1 in
        -o | --offline )        export OFFLINE=1
                                ;;
        -r | --remote_db )      export USE_REMOTE_DB=1
                                ;;
        -p | --port )           export PORT="$2"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
    esac
    shift
done


export HEROKU_CLI=/usr/bin/heroku

# Run the backend server via heroku local if it is available, otherwise gunicorn directly
if [ $OFFLINE ]; then
    echo "Running backend without network connection"
    sanic server.app

elif [ -f "$HEROKU_CLI" ]; then
    echo "$HEROKU_CLI is present"
    heroku local
else
    echo "$HEROKU_CLI does not exist"
    sanic server.app
fi

