#!/bin/bash
#
# This script sets up a Python 3 virtual environment in a directory .venv/
#   if it doesn't exist and installs all of the packages from
#   requirements.txt and requirements-dev.txt
#  into it.
#
#  In order for the backend sever to be set up properly you need to have Python 3.8.3
#   or higher installed and accessible as python3.
#
#  If you have this repo in a Dropbox, Google Drive, or some other online file syncing
#   service, after this setup you should move the .venv/ directory to somewhere else
#   and create a symoblic link to it here.

d="./.venv"
a=$d/bin/activate

if [[ ( ! -d "$d" )  &&  ( ! -L "$d" ) ]]; then
    mkdir $d
fi

if [ ! -f $a ]; then
     echo "Creating Python virtual environment in $d"
     python3 -m venv --clear $d
fi

if [ ! -f $a ]; then
    echo "could not create python environment"
    exit 1
fi

echo echo "source $a"
source $a

echo "attempting to update pip to latest version"
python -m pip install --upgrade pip

echo "installing backend dependencies (requirements.txt)"
pip install -r requirements.txt

echo "installing backend dev-dependencies (requirements-dev.txt)"
pip install -r requirements-dev.txt


if [ ! -f .env ] then;
    echo "copying .env.tmp to .env"
    cp .env.tmp .env
fi

