"""empty message

Revision ID: 607c65184e2b
Revises: None
Create Date: 2016-10-19 11:36:30.271631

"""

# revision identifiers, used by Alembic.
revision = '607c65184e2b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('strava_id', sa.Integer(),
                  autoincrement=False, nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('firstname', sa.String(), nullable=True),
        sa.Column('lastname', sa.String(), nullable=True),
        sa.Column('profile', sa.String(), nullable=True),
        sa.Column('strava_access_token', sa.String(), nullable=True),
        sa.Column('dt_last_active', pg.TIMESTAMP(), nullable=True),
        sa.Column('app_activity_count', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('strava_id')
    )
    op.create_table('activity',
                    sa.Column('id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('athlete_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('summary_polyline', sa.String(), nullable=True),
                    sa.Column('beginTimestamp', pg.TIMESTAMP(), nullable=True),
                    sa.Column('total_distance', sa.Float(), nullable=True),
                    sa.Column('elapsed_time', sa.Integer(), nullable=True),
                    sa.Column('time', pg.ARRAY(sa.Integer()), nullable=True),
                    sa.Column('polyline', sa.String(), nullable=True),
                    sa.Column('distance', pg.ARRAY(sa.Float()), nullable=True),
                    sa.Column('altitude', pg.ARRAY(sa.Float()), nullable=True),
                    sa.Column('velocity_smooth',
                              pg.ARRAY(pg.REAL()), nullable=True),
                    sa.Column('cadence', pg.ARRAY(sa.Integer()), nullable=True),
                    sa.Column('watts', pg.ARRAY(pg.REAL()), nullable=True),
                    sa.Column('grade_smooth',
                              pg.ARRAY(pg.REAL()), nullable=True),
                    sa.Column('dt_cached', pg.TIMESTAMP(), nullable=True),
                    sa.Column('dt_last_accessed',
                              pg.TIMESTAMP(), nullable=True),
                    sa.Column('access_count', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.strava_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('users')
    ### end Alembic commands ###
