"""empty message

Revision ID: 72566dc71c42
Revises: None
Create Date: 2016-08-25 15:27:29.531453

"""

# revision identifiers, used by Alembic.
revision = '72566dc71c42'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_user_data', postgresql.JSON(), nullable=True))
    op.drop_column('users', 'strava_token')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strava_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'strava_user_data')
    ### end Alembic commands ###
