"""empty message

Revision ID: c647dd716396
Revises: 72566dc71c42
Create Date: 2016-08-25 17:10:41.656913

"""

# revision identifiers, used by Alembic.
revision = 'c647dd716396'
down_revision = '72566dc71c42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
