name: Format

on: [push, pull_request]

jobs:
  check:
    name: Check changed/updated files
    outputs:
        files: ${{ steps.checkStep.outputs.files }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: checkStep
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "::set-output name=files::${{ steps.checkStep.outputs.added_modified }}"

  prettier-format:
    name: Format frontend (js/ts) source files with prettier
    needs: check
    if: contains(needs.check.outputs.files, 'frontend/src/')
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'

      - name: Format js/ts files
        run: |
          npm install --save-dev prettier
          npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-apply js/ts formatting
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  black-format:
    name: Format backend (py) files with black
    needs: check
    if: contains(needs.check.outputs.files, 'backend/heatflask/')
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: python -m pip install --upgrade pip black

      - name: Format py files
        run: ./black-format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-apply Python formatting
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name:
        run: |
          npm install
          npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build front-end for deployment
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test:
    name: Test output of check job
    needs: check
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Changed files:"
          echo "${{ needs.check.outputs.files }}"
