name: Format

on: [push, pull_request]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      paths: ${{ steps.changes.outputs.paths }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=paths::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"

  test:
    name: Test output of changedfiles job
    needs: changedfiles
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Changed files:"
          echo "${{ needs.changedfiles.outputs.paths }}"

  prettier-format:
    name: Format frontend (js/ts) source files with prettier
    needs: changedfiles
    if: contains(needs.changedfiles.outputs.paths, 'frontend/src/')
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'

      - name: Format js/ts files
        run: |
          npm install --save-dev prettier
          npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-apply js/ts/html formatting
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  black-format:
    name: Format backend (py) files with black
    needs: changedfiles
    if: contains(needs.changedfiles.outputs.paths, 'backend/heatflask/')
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: python -m pip install --upgrade pip black

      - name: Format py files
        run: ./.black-format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-apply Python formatting
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    if: github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
      - name:
        run: |
          npm ci
          npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build front-end for deployment
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


