name: Format

on: [push, pull_request]

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      paths: ${{ steps.changes.outputs.paths }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=paths::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"


  prettier-format:
    name: Format frontend (js/ts) source files with prettier
    needs: changedfiles
    if: contains(needs.changedfiles.outputs.paths, 'frontend/src/')
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'

      - name: Format js/ts files
        run: |
          npm install --save-dev prettier
          npm run format
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-apply js/ts/html formatting (Prettier)"
          git push


  black-format:
    name: Format backend (py) files with black
    needs: changedfiles
    if: contains(needs.changedfiles.outputs.paths, 'backend/heatflask/')
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install backend dependencies
        run: python -m pip install --upgrade pip black

      - name: Format py files
        run: |
          ./.black-format
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-apply Python formatting (Black)"
          git push


  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    if: contains('refs/heads/staging refs/heads/production', github.ref)
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run pydoc to create backend API documentation
        run: |
          python -m pip install pdoc
          pdoc -o ./dist/docs/backend/ ../backend/heatflask

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'
      - name:
        run: |
          npm ci
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "build frontend for deploy"
          git push
